FROM openjdk:8-jdk-slim

# Set environment variables
ENV SPARK_VERSION=3.4.1 \
    HADOOP_VERSION=3 \
    SPARK_HOME=/opt/spark

# Install dependencies
RUN apt-get update && \
    apt-get install -y curl wget bash git python3 python3-pip && \
    apt-get clean

# Download and install Spark
RUN wget https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
    tar -xvzf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
    mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} ${SPARK_HOME} && \
    rm spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz

# Download Spark Kafka connector
RUN mkdir -p ${SPARK_HOME}/jars && \
    wget -O ${SPARK_HOME}/jars/spark-sql-kafka.jar https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.4.1/spark-sql-kafka-0-10_2.12-3.4.1.jar && \
    wget -O ${SPARK_HOME}/jars/kafka-clients.jar https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.0/kafka-clients-3.4.0.jar

# Set environment variables
ENV PATH="${SPARK_HOME}/bin:${SPARK_HOME}/sbin:${PATH}"
ENV PYSPARK_PYTHON=python3

# Create a non-root user
RUN useradd -ms /bin/bash sparkuser
USER sparkuser
WORKDIR /home/sparkuser

# Default command
CMD ["spark-shell"]
